### ISSUE TITLE
rock-convert updated path

### ISSUE THREAD

**Issue by joaobrittoneto** [rock-core/tools-log_tools#10]
When using rock-convert, the new log file is saved in the updated folder present in the current working directory.
Shouldn't the updated folder be present in the log directory?

Doing `~/current/folder $ rock-convert ~/path/to/log/logfile.0.log --use-sample-time`
creates `~/current/folder/updated/logfile.0.log` instead of `~/path/to/log/updated/logfile.0.log`

**Comment by g-arjones** [comment]
This is a somewhat common behavior within the linux ecosystem.. You may change the output dir with the `-o, --output` argument

**Comment by doudou** [comment]
@joaobrittoneto if you're OK with the answer, think about closing the issue, thanks
